### ISSUE TITLE
NIM tab is reloaded every seconds.

### ISSUE THREAD

**Issue by yoshiokatsuneo** [june07/NIM#12]
NIM used to work like a charm.
But, it suddenly stopped working and NIM tab is reloaded every seconds, if I enable Auto mode.
There is no issue on manual mode.
I can just suspect it as an issue on 0.12.3.

Thank you.

**Comment by june07** [comment]
I will look into this asap!

**Comment by june07** [comment]
I have confirmed the issue on my end and a fix will be pushed soon.  In the
meantime you can install version 0.11 http://june07.com/nim11.  Both
versions can be installed in parallel as long as one of them is disabled.

I will update you once the fix is pushed.

**Comment by june07** [comment]
The fix has been pushed both here and to the Chrome Web Store.  Please confirm when you get a chance that it's working for you...

**Comment by yoshiokatsuneo** [comment]
I tried 0.12.4, but the issue is no fixed. The NIM tab restart continuously.

**Comment by june07** [comment]
Try to uninstall and then reinstall.  Also did you see my message regarding
version 0.11?

**Comment by yoshiokatsuneo** [comment]
I uninstalled and installed the 0.12.4, but the issue still exist...
I installed 0.11, and the 0.11 works without problem.
Thank you !
